import React from 'react';

export const Plats = () => {
    return (
        <div>
            <h1>PLATS</h1>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quidem vitae impedit fugiat voluptatem delectus, commodi molestiae neque eligendi quis ex perferendis facere dolorum distinctio voluptates quam consequatur reprehenderit omnis!
            Quo aliquid vero cupiditate qui, quod dignissimos repudiandae praesentium officia. Reprehenderit odit, earum, adipisci sequi expedita, quia dolorum ducimus cum unde ab aut amet iusto quibusdam sunt tempora corporis magni?
            Voluptatibus quo, libero ea distinctio laborum, et quaerat perferendis exercitationem iusto maxime sunt corporis odit voluptatem recusandae delectus esse ipsam temporibus, rem porro incidunt tempora dolor facilis vel aliquam! Sit!
            Nostrum reiciendis, excepturi et vero explicabo hic cumque delectus perspiciatis distinctio ea exercitationem voluptatibus praesentium animi at architecto, inventore, eum veniam nemo. Nam officia provident debitis tenetur, quidem vero tempora.
            Sequi eius temporibus cumque excepturi ratione qui possimus repellendus quis delectus placeat, tempore alias dignissimos quaerat doloremque sit, molestias ipsa. Nisi ex, molestias ullam aut dolor tenetur incidunt velit tempore!
            Omnis soluta reprehenderit ullam, eos quidem harum dolorum, similique id nesciunt non natus corrupti, aspernatur facilis eveniet reiciendis voluptates. Labore, fuga ipsum? Quo architecto temporibus nemo harum sit, est aliquid.
            Nostrum ipsam ad reiciendis eos aperiam eveniet quo id sequi assumenda dolore adipisci ipsa repellendus, nulla laboriosam fugit! In, odio recusandae earum labore sed temporibus libero? Optio sit fuga ratione.
            Cumque fugiat nihil consequatur, temporibus alias quidem non facilis reiciendis hic voluptatem soluta quam dolores beatae excepturi harum unde eius iste tempore eum facere distinctio ut rerum. Laudantium, suscipit eveniet!
            Qui in ducimus officia accusantium quo at. Obcaecati, odit velit temporibus qui assumenda asperiores quia quibusdam? Dolorum, ipsa repudiandae exercitationem quasi veritatis commodi explicabo perspiciatis, accusantium architecto adipisci nulla harum?
            Possimus delectus, reprehenderit ut esse officiis similique blanditiis velit doloribus? Voluptas, fuga possimus voluptate rem unde tempora, magni accusantium dicta rerum ullam earum aliquam laborum temporibus. Officiis voluptate ipsum assumenda.
            Perspiciatis earum nisi aperiam beatae commodi exercitationem rem eum numquam repellendus iure. Reiciendis mollitia sint fuga ut magni odio iusto tempora. Tempore labore debitis quis ad, quae iure quidem veritatis.
            Voluptatibus nemo expedita deleniti modi, molestias atque temporibus corporis, facere, suscipit nesciunt ut? Fuga est autem, culpa harum sunt totam sit praesentium iure odit quidem provident facilis accusamus ipsam eaque?
            Totam deserunt incidunt non, sint corrupti earum reiciendis. A libero cum perferendis possimus, quam odit officia. Illo aliquam, obcaecati unde expedita id ipsa a esse vitae iure consectetur voluptate aspernatur.
            Sed, laudantium! Harum ullam maiores voluptatem eius doloremque impedit accusantium assumenda, quidem dicta omnis debitis officia ex? Quis dolor culpa voluptatum aliquam a impedit eaque possimus nemo omnis. Tempora, repellat?
            Ut similique natus facilis, eligendi voluptatum adipisci voluptates quisquam hic beatae placeat voluptatibus ipsam quam? Non expedita corporis eum enim voluptate! Dolorum soluta ipsum officia necessitatibus a voluptates quos autem!
            Aspernatur assumenda, rerum, incidunt soluta corporis voluptatum aliquid non ipsa minima consequatur reiciendis blanditiis in accusamus est corrupti doloribus magni nesciunt? Voluptatum hic quasi eius perferendis reiciendis veniam, explicabo aliquid!
            Nesciunt sapiente ipsa officiis non totam quaerat dolorum asperiores velit esse commodi, natus quam amet dolor ex iusto necessitatibus voluptas quia ab ipsum voluptates modi laborum expedita ea! Omnis, pariatur.
            A eum tempore, perspiciatis earum eius reprehenderit repellendus minus nam molestias expedita eaque adipisci suscipit numquam, culpa perferendis unde deserunt veniam, itaque qui architecto totam debitis mollitia aspernatur asperiores. Beatae.
            Eveniet iusto, accusantium commodi ad magnam omnis distinctio quos aspernatur necessitatibus exercitationem ducimus amet dolores cumque fugit. Voluptatibus cupiditate sapiente beatae omnis, tempore vero ad delectus rem. Enim, laudantium fuga!
            Id dolores ipsam inventore repudiandae debitis provident, repellendus doloribus eum minus a natus libero, eius placeat impedit deleniti totam deserunt facere voluptates veniam ratione quod modi tempore. Eaque, saepe accusamus?
            Expedita porro cupiditate incidunt illo placeat illum commodi. Doloribus totam sunt ducimus quidem eum, omnis illo obcaecati deleniti consequatur! Sint dolorum cumque autem veritatis itaque id soluta, labore nulla voluptates.
            Voluptatem, dicta maxime ex incidunt molestias asperiores laudantium est modi pariatur rem tenetur itaque neque ab odio maiores, ipsam fugiat labore. Eius corporis optio consequatur provident, exercitationem totam accusantium asperiores?
            Adipisci ipsam soluta accusantium odio, id explicabo facilis quibusdam assumenda culpa dolorum aspernatur voluptas sint ad sit quos repudiandae dolores amet ab. Sed laboriosam, debitis illum eos officia sunt dolorum!
            Officiis quae dicta commodi dolores tempora odit quibusdam consectetur at necessitatibus reiciendis dolore repudiandae nisi similique fugiat, fuga, vitae, delectus incidunt ratione rerum corrupti a aspernatur inventore sint? Amet, nam.
            Eveniet laboriosam numquam id voluptatibus. Rem saepe qui odio optio voluptatibus aut aperiam quam vero at, atque et dicta error doloremque quo magni quasi accusamus, inventore possimus molestias tenetur voluptates?
            Praesentium eaque quia facere recusandae dicta sequi at debitis voluptatum veritatis libero nobis voluptate perspiciatis tempora, in aut, modi distinctio magnam? Assumenda nesciunt suscipit illo maiores eum modi cum quaerat.
            Repudiandae quaerat earum cupiditate, deserunt optio molestiae qui quod. Vitae quisquam qui, nesciunt, alias consequuntur officiis eius repellat consectetur voluptatem quo, totam minima illo. Explicabo nihil reiciendis ex expedita ipsa?
            Laudantium fugit reiciendis placeat ipsam, a consequatur neque facilis! Fugit iste error, voluptas placeat dolor dicta deleniti eveniet ut, esse culpa sed voluptatum, suscipit odit iusto sint dolore illum reiciendis.
            Officia at eaque sequi nemo, explicabo facilis tempore totam quod? Possimus animi quae eius a optio asperiores et sequi culpa quas? Incidunt vel iste possimus adipisci atque error architecto placeat.
            Pariatur eum nam expedita molestiae magnam dolorum dolor velit et sint, voluptate quis necessitatibus assumenda rem, similique labore enim praesentium, nihil natus tempore culpa inventore quos nostrum? Magnam, sed mollitia.
            Laborum harum illum quisquam, iusto est ex nisi! Dicta laudantium sunt nihil fugit? Sequi quia eos asperiores doloremque suscipit minima ratione blanditiis corporis maxime sed corrupti modi, laborum ipsum ea?
            Libero numquam molestias provident itaque ipsum aut at nihil officia error perspiciatis illo deserunt repellendus dolorum rerum quos dolores, ab vero cumque voluptates maxime amet minima! Distinctio hic ex vel?
            Voluptatibus debitis placeat eligendi dolore porro architecto ab harum voluptatum labore quasi eos, fugiat, nihil molestias accusantium ex quam, nemo dolor sunt rem recusandae ut? Sunt placeat doloribus assumenda corrupti.
            Possimus sunt, beatae quae accusantium sit maxime vero facilis obcaecati rem et corporis omnis cupiditate reiciendis quas suscipit debitis nobis a nam laborum, asperiores vel qui quidem tenetur illo! Nam?
            Dolorum excepturi autem, soluta alias quos quod eligendi perferendis repellendus illo! Laboriosam soluta possimus in labore nihil, amet distinctio! Tempore quia quidem perspiciatis nobis error quod aliquam adipisci veniam ducimus.
            Maiores dolorum molestias, explicabo quibusdam, sapiente alias, minus fugit ex ratione excepturi est. Pariatur repudiandae incidunt dicta facere exercitationem quos, sint rerum cum quod debitis, quia nihil autem dolorum similique!
            Suscipit dolore voluptas perferendis cumque delectus ullam placeat sit dolorum molestiae, quos, hic autem doloribus, reiciendis harum voluptatem commodi maiores architecto nam. Quos aut accusantium ipsam exercitationem. Placeat, doloribus asperiores.
            Rerum repellendus a aspernatur voluptates dolorum quidem illum modi vel quia unde, blanditiis inventore voluptatem impedit ipsa provident maiores, aliquid numquam dolore necessitatibus sed quasi laborum. Illo ducimus voluptates repudiandae.
            Cupiditate incidunt delectus ut repellendus odio officiis molestias sint unde ullam minus debitis accusamus animi culpa velit nisi, sed officia in exercitationem quam maiores voluptatibus distinctio. A quaerat debitis voluptatem!
            Neque laborum blanditiis quos eos distinctio, magnam eius quasi dicta numquam tempore suscipit nemo laudantium qui adipisci fugit debitis perspiciatis ratione, totam deleniti modi deserunt odit? Ea ex nemo natus!
            Aliquam nulla sunt necessitatibus ex nisi voluptatibus reprehenderit dolorum assumenda consequatur, ullam ipsa, commodi corrupti eaque, voluptate nihil. Deserunt quos eius rerum officia necessitatibus beatae distinctio vero nobis! Magni, repudiandae?
            Consequatur sed quos quod dicta quidem cum delectus cumque doloremque, officia magni eligendi porro fugiat ducimus deserunt voluptates illum sint numquam incidunt ipsam quae maxime libero alias eveniet! Praesentium, necessitatibus.
            Natus provident commodi est corrupti tenetur repellendus et maiores quos recusandae eaque nostrum libero optio ad incidunt blanditiis, quam, error perferendis qui cumque! Reprehenderit, explicabo molestias recusandae illum distinctio numquam?
            Esse magnam voluptatem dolorum debitis ratione pariatur sequi! Deleniti, error necessitatibus modi totam tenetur nemo corrupti cumque! Ut maxime accusantium obcaecati voluptas reiciendis. Laboriosam vero, recusandae nihil ex nisi alias.
            Dolores pariatur libero ab saepe magni odio cupiditate iusto rerum sit exercitationem soluta tempore quae obcaecati perferendis numquam praesentium accusantium, iure voluptatum suscipit maiores reiciendis, illum mollitia omnis? Odio, fugit.
            Ab neque ducimus fuga totam, eveniet exercitationem minima dignissimos, veniam, consequuntur iste aliquam optio possimus eligendi. A reprehenderit laborum eveniet dolore eius optio, ipsam aut aliquam fugiat, quam rem porro.
            Dolores a, eos est odit dignissimos voluptate repellat impedit ducimus animi expedita facere in deleniti nobis, tenetur, adipisci assumenda! Error necessitatibus cum sapiente obcaecati! Nam quia optio iusto sapiente hic.
            Pariatur illum veritatis impedit nisi recusandae atque sit et dolorum quisquam sed explicabo harum neque repudiandae quas necessitatibus tempore reprehenderit corrupti, eius eaque totam tempora, vel, facere molestiae. Iure, reiciendis!
            Ducimus mollitia alias nemo tempore nisi ullam nulla magnam dolorum accusantium a nihil, facere iste laboriosam corporis reprehenderit eaque, quo totam natus harum cum rem voluptate! Id ad recusandae cumque?
            Ab obcaecati eos, reiciendis ullam voluptatibus earum iste officia suscipit perferendis voluptas eius nihil dolor pariatur a. Repellendus, nisi qui dolorem repudiandae veniam illo expedita, quasi cupiditate laudantium rem enim?
        </div>
    );
};

// export default Plats;